using System.Collections.ObjectModel;
using System.Windows.Input;
using Opus.DataAnnotations;
using Opus.Samples.Controls;

namespace Opus.Samples.Models
{
    /// <summary>
    ///   This class is used to represent a meta data class to just place meta data on your model
    ///   in many cases you may need to place metadata annotations on classes that were generated
    ///   in our case, let's pretend the PersonModel class was autogenerated
    /// </summary>
    [FieldGrouping(Name = "Orders", Order = 3, LastChildFill = true)]
    [FieldGrouping(Name = "Contact", Order = 0)]
    [FieldGrouping(Name = "Phone Numbers", Order = 1)]
    [FieldGrouping(Name = "Address", Order = 2)]
    
    public static class PersonMetadata
    {
        [DisplayControlTextbox(Name = "First Name", Group = "Contact", InputScope = InputScopeNameValue.PersonalFullName
            )] public static string FirstName;

        [DisplayControlTextbox(Name = "Last Name", Group = "Contact", InputScope = InputScopeNameValue.PersonalFullName)
        ] public static string LastName;

        [DisplayControlTextbox(Name = "Email Address", Group = "Contact",
            InputScope = InputScopeNameValue.EmailNameOrAddress)] public static string EmailAddress;

        [DisplayControlTextbox(Name = "Phone 1", Group = "Phone Numbers",
            InputScope = InputScopeNameValue.TelephoneNumber)] public static string Phone1;

        [DisplayControlTextbox(Name = "Phone 2", Group = "Phone Numbers",
            InputScope = InputScopeNameValue.TelephoneNumber)] public static string Phone2;

        [DisplayControlTextbox(Name = "Address 1", Group = "Address", InputScope = InputScopeNameValue.AddressStreet)] public static string Address1;

        [DisplayControlTextbox(Name = "Addres 2", Row = 1, Group = "Address",
            InputScope = InputScopeNameValue.AddressStreet)] public static string Address2;

        [DisplayControlTextbox(Name = "City", Row = 1, Group = "Address", InputScope = InputScopeNameValue.AddressCity)] public static string City;

        [DisplayControlTextbox(Name = "State", Row = 1, Group = "Address",
            InputScope = InputScopeNameValue.AddressStateOrProvince)] public static string State;

        [DisplayControlTextbox(Name = "Zip", Row = 1, Group = "Address", InputScope = InputScopeNameValue.PostalCode)] public static string Zip;

        [DisplayControlGrid(Name = "Orders", Group = "Orders", EntityType = typeof (OrderModel))] public static
            ObservableCollection<OrderModel> Orders;

        [DisplayControlTextbox(Name = "Total Sales", Group = "Contact", Order = 99, StringFormat = "{0:c}")] public static double? TotalSales;

        [DisplayCustomControl(Name = "My Custom Control", Group = "Contact", Order = 100, Row = 1,
            ControlType = typeof (MyCustomControl))] public static string MyCustomerProperty;
    }
}